version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: postgres-bash
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    networks:
      - microservice

volumes:
  pgdata:

networks:
  microservice: